!include ../plantuml-style/sketchy-outline.puml

!include ../plantuml-style/core.puml

title Cpu0后端架构图

LAYOUT_TOP_DOWN
' LAYOUT_LEFT_RIGHT

' --------------------LLVM层关系--------------------
package LLVM后端 {

    entity LLVM_BACKEND {
        LLVM的后端
    }
}


' --------------------Cpu0层一级类与关系--------------------
package 第一次关系 {

    ' 注册类与LLVM之间的关系
    Cpu0TargetMachine                   -up->           LLVM_BACKEND

    class Cpu0TargetMachine {
        注册对象的基类,基类中
        有Cpu0SubTarget对象
        ----
        + virtual getSubtargetImpl()
        + virtual createPassConfig()
        + virtual getObjFileLowering()
        ----
        - Cpu0ABIInfo ABI
        - Cpu0Subtarget DefaultSubtarget
    }

    note left of Cpu0TargetMachine
        Cpu0TargetMachine通过继承LLVMTargetMachine,
        注册到LLVM的后端,使得LLVMM可以自由的调用
        Cpu0的后端,对外提供功能的是Cpu0Subtarget这个类型
        ----
        getSubtargetImpl:通过该函数向LLVM后端传递Cpu0Subtarget
        ----
        createPassConfig:通过该函数向LLVM后端传递Cpu0PassConfig
        ----
        getObjFileLowering:通过该函数向LLVM后端传递Cpu0TargetObjectFile
    endnote

    class Cpu0ebTargetMachine {
        Cpu0eb架构(只负责注册)
    }

    class Cpu0elTargetMachine {
        Cpu0el架构(只负责注册)
    }

    note "对外注册\
      Cpu0ebTargetMachine与Cpu0elTargetMachine\
      两个类,使得llc可以调用起Cpu0的后端" as ExternNote

    ' Cpu0TargetMachine类关系(继承关系)
    Generalize(Cpu0ebTargetMachine, Cpu0TargetMachine, up)
    Generalize(Cpu0elTargetMachine, Cpu0TargetMachine, up)

    ' 注释
    NOTE_LINEK(ExternNote, Cpu0ebTargetMachine, up)
    NOTE_LINEK(ExternNote, Cpu0elTargetMachine, up)
}


' --------------------Cpu0层二级类与关系--------------------
package 第二层关系 {

    class Cpu0Subtarget {
        对外真正提供功能的类
    }

    note top of Cpu0Subtarget #red
        Cpu0后端核心类
    endnote

    class Cpu0ABIInfo {
        描述ABI的类
    }

    class Cpu0PassConfig {

    }

    class Cpu0TargetObjectFile {

    }

    ' 聚合关系
    Composition(Cpu0Subtarget, Cpu0TargetMachine, up)
    Composition(Cpu0ABIInfo, Cpu0TargetMachine, up)

    ' 依赖关系
    Dependency(Cpu0PassConfig, Cpu0TargetMachine, up)
    Dependency(Cpu0TargetObjectFile, Cpu0TargetMachine, up)
}


' --------------------Cpu0层三级类与关系--------------------
package 第三层关系 {

    class Cpu0InstrInfo {
        指令集相关的接口类
    }


    class Cpu0FrameLowering {
        堆栈指针相关的类接口
    }

    class Cpu0SEFrameLowering {
        堆栈指针相关的类真正实现
    }

    class Cpu0TargetLowering {
        指令合法化类
    }

    class Cpu0SEDAGToDAGISel {

    }

    class Cpu0DAGToDAGISel {

    }

    class Cpu0LongBranch {
        Cpu0的PASS优化
        ----
    }

    class Filler {
        Cpu0的PASS优化
        ----
    }

    struct DelJmp {
        Cpu0的PASS优化
        ----
    }

    struct Inserter {
        Cpu0的PASS优化
        ----
    }

    note "通过重写Cpu0PassConfig::addInstSelector\
          函数添加这个PASS" as PassConfig_Inst

    note "通过重写Cpu0PassConfig::addPreEmitPass\
          函数添加这3个PASS" as PassConfig_EmitPass

    note "通过重写Cpu0PassConfig::addPreRegAlloc\
          函数添加这个PASS" as PassConfig_RegAlloc

    ' Cpu0PassConfig与其他PASS优化关系(依赖关系)
    Dependency(Cpu0SEDAGToDAGISel, Cpu0PassConfig, up)
    Dependency(Cpu0LongBranch, Cpu0PassConfig, up)
    Dependency(Filler, Cpu0PassConfig, up)
    Dependency(DelJmp, Cpu0PassConfig, up)
    Dependency(Inserter, Cpu0PassConfig, up)
    ' Cpu0PassConfig注释
    NOTE_LINEK(PassConfig_Inst, Cpu0SEDAGToDAGISel, up)
    NOTE_LINEK(PassConfig_EmitPass, Cpu0LongBranch, up)
    NOTE_LINEK(PassConfig_EmitPass, Filler, up)
    NOTE_LINEK(PassConfig_EmitPass, DelJmp, up)
    NOTE_LINEK(PassConfig_RegAlloc, Inserter, up)

    ' 组合关系
    Composition(Cpu0InstrInfo, Cpu0Subtarget, up)
    Composition(Cpu0SEFrameLowering, Cpu0Subtarget, up)
    Composition(Cpu0TargetLowering, Cpu0Subtarget, up)

    ' 继承关系
    Generalize(Cpu0SEFrameLowering, Cpu0FrameLowering, up)
    Generalize(Cpu0SEDAGToDAGISel, Cpu0DAGToDAGISel, up)
}


' --------------------Cpu0层四级类与关系--------------------
package 第四级关系 {

    class Cpu0SEInstrInfo {
        Cpu032/64位指令集真正实现类
    }

    class Cpu0SERegisterInfo {
        Cpu0真正的寄存器信息类
    }

    class Cpu0RegisterInfo {
        寄存器相关的类
    }

    ' 继承关系
    Generalize(Cpu0SEInstrInfo, Cpu0InstrInfo, up)
    Generalize(Cpu0SERegisterInfo, Cpu0RegisterInfo, up)

    ' 组合关系
    Composition(Cpu0RegisterInfo, Cpu0InstrInfo, up)
}


' --------------------Cpu0层五级类与关系--------------------
package 第五层关系 {
    class Cpu0AnalyzeImmediate {

    }

    class Cpu0FunctionInfo {

    }

    Dependency(Cpu0AnalyzeImmediate, Cpu0SEInstrInfo, up)
    Dependency(Cpu0FunctionInfo, Inserter, up)
    Dependency(Cpu0FunctionInfo, Cpu0DAGToDAGISel, up)
    Dependency(Cpu0FunctionInfo, Cpu0TargetLowering, up)
    Dependency(Cpu0FunctionInfo, Cpu0LongBranch, up)
    Dependency(Cpu0FunctionInfo, Cpu0RegisterInfo, up)
    Dependency(Cpu0FunctionInfo, Cpu0SEFrameLowering, up)

}


note "类图中的SE表示standard edition,即标准版的意思" as CPU0