@startuml

title TableGen类型分析

!include ../plantuml-style/sketchy-outline.puml
!include ../plantuml-style/core.puml
!include ../plantuml-style/class-relation.puml

class TGParser {
    - Records
}

note left of TGParser
    TD文件词法分析器
endnote

class RecordKeeper {
    - Classes
        |_** std::map<std::string, Record>**
}

note left of RecordKeeper
    RecordKeeper是所有Record封装的一个hash表,
    <b><color:OrangeRed>所有Record都存储在Classes中</color>
endnote

class DefInit {

}

class RecordVal {

}

note top of RecordVal
    该类型记录命名, 类型, 值已经源码位置
endnote

' ====================
class Init {

}

class TypedInit {

}

class UnsetInit {

}

' ====================
class Record {
    {static} - LastID
    - Name
    - TemplateArgs
    - Values
    - Assertions
    - SuperClasses
    - ID
}

note left of Record
    Name的类型为Init
    ----
    Template的类型为Init
    ----
    Values的类型为RecordVal
endnote


' 类关系

' ----- TGParser -----
Composition(RecordKeeper,       TGParser, up)

' ----- Record -----
Composition(Init,               Record, up)
Dependency(RecordKeeper,        Record, down)
Composition(Record,             RecordKeeper, up)
Composition(RecordVal,          Record, up)


' ----- Init -----
Generalize(TypedInit,           Init, up)
Generalize(UnsetInit,           Init, up)

Generalize(BitInit,             TypedInit,  up)
Generalize(BitsInit,            TypedInit,  up)
Generalize(CondOpinit,          TypedInit,  up)
Generalize(DagInit,             TypedInit,  up)
Generalize(DefInit,             TypedInit,  up)
Generalize(FieldInit,           TypedInit,  up)
Generalize(FoldOpInit,          TypedInit,  up)
Generalize(IntInit,             TypedInit,  up)
Generalize(IsAOpInit,           TypedInit,  up)
Generalize(ListInit,            TypedInit,  up)
Generalize(OpInit,              TypedInit,  up)
Generalize(StringInit,          TypedInit,  up)
Generalize(VarBitInit,          TypedInit,  up)
Generalize(VarDefInit,          TypedInit,  up)
Generalize(VarInit,             TypedInit,  up)
Generalize(VarListElementInit,  TypedInit,  up)

' ----- OpInit -----
Generalize(BinOpInit,           OpInit, up)
Generalize(TernOpInit,          OpInit, up)
Generalize(UnOpInit,            OpInit, up)




Aggregation(DefInit,            Record, up)




@enduml